version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
        - "9010:9010"
        - "9020:9020"

  spanner-setup:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:332.0.0-slim
    command: >
      bash -c 'gcloud config configurations create emulator &&
              gcloud config set auth/disable_credentials true &&
              gcloud config set project $${PROJECT_ID} &&
              gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
              gcloud config set auth/disable_credentials true &&
              gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1 &&
              gcloud spanner databases create $${DATABASE_NAME_DEVELOPMENT} --instance=$${INSTANCE_NAME} &&
              gcloud spanner databases create $${DATABASE_NAME_TEST} --instance=$${INSTANCE_NAME}'
    environment:
      PROJECT_ID: "rails-cloud-spanner-project"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      INSTANCE_NAME: "rails-cloud-spanner-instance"
      DATABASE_NAME_DEVELOPMENT: "rails-cloud-spanner-dev-db"
      DATABASE_NAME_TEST: "rails-cloud-spanner-test-db"
  spanner-cli:
    image: sjdaws/spanner-cli:v1.0.0
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9010"
    command: ['sh', '-c', 'echo this container keep running && tail -f /dev/null']

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml