default: &default
  adapter: "spanner"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  project: "rails-cloud-spanner-project"
  instance: "rails-cloud-spanner-instance"
  emulator_host: spanner:9010

development:
  <<: *default
  database: "rails-cloud-spanner-dev-db"

test:
  <<: *default
  database: "rails-cloud-spanner-test-db"

production:
  <<: *default
  database: "rails-cloud-spanner-prod-db"
